<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>deferred_service_response_cpp</name>
  <version>0.0.0</version>
  <description>Deferred service responses in C++ without multithreading, allows for async service providers</description>
  <maintainer email="36795178+SuperJappie08@users.noreply.github.com">SuperJappie08</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>advanced_demo_interfaces</build_depend>
  <build_depend>example_interfaces</build_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>rclcpp_components</build_depend>

  <exec_depend>advanced_demo_interfaces</exec_depend>
  <exec_depend>example_interfaces</exec_depend>
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <!-- FIXME: Temporary until add_two_ints_delay_server has been made -->
  <exec_depend>composition</exec_depend>
  <exec_depend>demo_nodes_cpp</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
