name: CI Advanced ROS 2 Demos

on: [push, pull_request]

jobs:
  ament_lint:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-ros-${{ matrix.ros_distro }}-ros-base-latest

    strategy:
      fail-fast: false
      matrix:
        package: [deferred_service_response_cpp]
        linter:
          - xmllint
          - copyright
          - pep257
          - flake8
          - uncrustify
          - cppcheck
          - cpplint
          - lint_cmake
        ros_distro: [humble, jazzy, kilted, rolling]
        include:
          - ros_distro: humble
            ubuntu: jammy
          - ros_distro: jazzy
            ubuntu: noble
          - ros_distro: kilted
            ubuntu: noble
          - ros_distro: rolling
            ubuntu: noble
        exclude:
          - ros_distro: humble
            linter: uncrustify

    steps:
      - name: Checkout launch_ros2_control
        uses: actions/checkout@v4
      - name: Run Linter
        uses: ros-tooling/action-ros-lint@v0.1
        with:
          linter: ${{ matrix.linter }}
          distribution: ${{ matrix.ros_distro }}
          package-name: ${{ matrix.package }}
        env:
          AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: true

  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-ros-${{ matrix.ros_distro }}-ros-base-latest

    needs: ament_lint

    strategy:
      matrix:
        ros_distro: [humble, jazzy, kilted, rolling]
        include:
          - ros_distro: humble
            ubuntu: jammy
          - ros_distro: jazzy
            ubuntu: noble
          - ros_distro: kilted
            ubuntu: noble
          - ros_distro: rolling
            ubuntu: noble

    steps:
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: |
            deferred_service_response_cpp
          target-ros2-distro: ${{ matrix.ros_distro }}
          # FIXME(SuperJappie08): Temporarily disable tests on humble, since uncrustify version differs
          skip-tests: ${{ matrix.ros_distro == 'humble' }}
        env:
          AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: true
